### ISSUE TITLE
Accept optional attibutes from RIPE-DB

### ISSUE THREAD

**Issue by donnerhacke** [irrtoolset/irrtoolset#47]
$ whois -h whois.ripe.net  AS3333 | sed -n '/^aut-num/,/^source/p' | rpslcheck 2>&1 | fgrep '***'
***Error: unknown attribute status of class aut-num
***Error: unknown attribute created of class aut-num
***Error: unknown attribute last-modified of class aut-num

In consequence, rtconfig and peval does ignore the object in the "cache-file" without modification.
After testing the modified object is not accepted at RIPE (due to missing attibutes)

**Comment by nickhilliard** [comment]
> ***Error: unknown attribute status of class aut-num

fixed in 5cd9ac8.

> ***Error: unknown attribute created of class aut-num
> ***Error: unknown attribute last-modified of class aut-num

was fixed in d3787ba9 (commit date 2015-04-10 - you must be running a very old version of irrtoolset).

**Comment by donnerhacke** [comment]
I'm using "Tag distribution for 5.0.1 release", which is the latest "release" in this project (according to tags). It's the version, which is current in various distributions like FreeBSD.

May be it's time to tag a new release?
