### ISSUE TITLE
got segmentation fault when running the rtconfig examples

### ISSUE THREAD

**Issue by ZhijiaCHEN** [irrtoolset/irrtoolset#49]
Hello,

I am new to the irrtoolset. I studied RPSL recently I and I want to see what configurations would be generated from RPSL objects. So I started by trying to play around with the examples, but I got segmentation error.

I am running on Ubuntu 18.04, and I followed the installation guide to install the toolset. Could someone help me to make the examples working? Thanks!

**Comment by nickhilliard** [comment]
fixed in ffaa08c

**Comment by nickhilliard** [comment]
this is a compiler bug in GCC.  You can either upgrade to HEAD on the git repo, or else you can work around the bug by using the following:

$ export CFLAGS "-O2 -fno-tree-vrp"
$ export CXXFLAGS "-O2 -fno-tree-vrp"
$ ./configure
$ make

**Comment by ZhijiaCHEN** [comment]
> 
> 
> this is a compiler bug in GCC. You can either upgrade to HEAD on the git repo, or else you can work around the bug by using the following:
> 
> $ export CFLAGS "-O2 -fno-tree-vrp"
> $ export CXXFLAGS "-O2 -fno-tree-vrp"
> $ ./configure
> $ make

It works! Thanks!
