### ISSUE TITLE
Integer overflow during output

### ISSUE THREAD

**Issue by afpd** [irrtoolset/irrtoolset#51]
There is an integer overflow during output. 
Expand AS-SET to ASN list:
$ peval -no-as -h whois.radb.net AS-INTELSATUS | tr -d '('  | tr -d ')'  | tr ' ' '\n' | sort 1> /tmp/AS-INTELSATUS.peval
Grep for minus sign:
$ grep '-' /tmp/AS-INTELSATUS.peval
AS-94914185

Expand using netcat:
$ echo '!iAS-INTELSATUS,1\n' | nc whois.radb.net 43 | tr -d 'C' | tr ' ' '\n' | sort > /tmp/AS-INTELSATUS.netcat

Compare outputs:
$ diff -u /tmp/AS-INTELSATUS.netcat /tmp/AS-INTELSATUS.peval
--- /tmp/AS-INTELSATUS.netcat   2019-01-02 20:06:57.644537396 -0500
+++ /tmp/AS-INTELSATUS.peval    2019-01-02 20:07:25.012212642 -0500
@@ -1,5 +1,4 @@
 
-A82782
 AS10022
 AS10028
 AS10029
@@ -6779,7 +6778,6 @@
 AS4195
 AS41979
 AS41999
-AS4200053111
 AS42013
 AS4202
 AS42028
@@ -9753,6 +9751,7 @@
 AS9488
 AS9489
 AS9491
+AS-94914185
 AS9492
 AS9493
 AS9494

Overflow happens like this
printf("%i\n", atoi("4200053111"));

Problem located in the 

~/irrtoolset$ git diff
diff --git a/src/rpsl/rpsl_asnum.hh b/src/rpsl/rpsl_asnum.hh
index 7d351c6..ed3f26d 100644
--- a/src/rpsl/rpsl_asnum.hh
+++ b/src/rpsl/rpsl_asnum.hh
@@ -6,22 +6,22 @@ extern bool opt_asdot;
 inline int asnum_string(char *buf, unsigned int asno)
 {
    if (asno > 65535 && opt_asdot)
-      return sprintf(buf, "AS%d.%d", asno>>16, asno&0xffff);
+      return sprintf(buf, "AS%u.%u", asno>>16, asno&0xffff);
    else
-      return sprintf(buf, "AS%d", asno);
+      return sprintf(buf, "AS%u", asno);
 }
 
 inline int asnum_string_dot(char *buf, unsigned int asno)
 {
    if (asno > 65535)
-      return sprintf(buf, "AS%d.%d", asno>>16, asno&0xffff);
+      return sprintf(buf, "AS%u.%u", asno>>16, asno&0xffff);
    else
-      return sprintf(buf, "AS%d", asno);
+      return sprintf(buf, "AS%u", asno);
 }
 
 inline int asnum_string_plain(char *buf, unsigned int asno)
 {
-   return sprintf(buf, "AS%d", asno);
+   return sprintf(buf, "AS%u", asno);
 }
 
 #endif

I will prepare pull request for that.

**Comment by nickhilliard** [comment]
fixed in commit f94d76cd869dd69cb306d86e1e729037ca0adb08
