### ISSUE TITLE
peval disk flowers

### ISSUE THREAD

**Issue by randyqx** [irrtoolset/irrtoolset#53]
Ubuntu 18.04 fully patched
irrtoolset 5.01
```
%  peval -version
peval irrtoolset-5.0.1
% peval -s RGNET AS-RG-SEA
Segmentation fault (core dumped)
```
for all queries.  worked just two weeks ago.  before i chase the core, has there been some change i missed?

**Comment by nickhilliard** [comment]
can you git-clone master from https://github.com/irrtoolset/irrtoolset.git and see if that works?  There were a bunch of fixes implemented between 5.0.1 and -current.
