### ISSUE TITLE
Request for a new 5.0.2 release

### ISSUE THREAD

**Issue by tomaszmrugalski** [irrtoolset/irrtoolset#55]
Hi there. Not really involved myself, but asking this for a friend. The latest 5.0.1 version does not work on Ubuntu. A friend tested on Ubuntu 16.04 and I tested on 18.04 both compilation failed with an error complaining about 'undefined reference to `rpslparse(void*)'.

This problem is fixed on master. It would be very useful to do a maintenance release.

If you disagree, feel free to close this issue.

**Comment by nickhilliard** [comment]
5.1.2 now released.

irrtoolset is probably not a good idea in 2019.  Better to use e.g. bgpq3.
