### ISSUE TITLE
peval, Segmentation fault (core dumped), Centos 8.

### ISSUE THREAD

**Issue by kronby** [irrtoolset/irrtoolset#56]
I get the core dump file when I try to get the IP routing prefixes for as-set or AS via utility peval.
Used latest irrtoolset, the same situation with version 5.1.2, utilities compiled on Centos 8.
In attachment Core dump file, file with message that I received in /var/log /messages and config.log file.
Execution:
[root@cacti-core tmp]# peval -no-as AS-GOLAS
((AS51789 ))
[root@cacti-core tmp]# peval -no-route-set AS-GOLAS
Segmentation fault (core dumped)

[centos8-messages-peval.txt](https://github.com/irrtoolset/irrtoolset/files/3823538/centos8-messages-peval.txt)
[config.log](https://github.com/irrtoolset/irrtoolset/files/3823539/config.log)
[core-peval.10282.dump.log](https://github.com/irrtoolset/irrtoolset/files/3823552/core-peval.10282.dump.log)

**Comment by afpd** [comment]
As a workaroung, disabling compiler optimisation (-O0) may help

1) autoreconf -i
2) export CFLAGS='-O0'
3) ./configure
4) make -j8
5) irrtoolset-master$ src/peval/peval AS-GOLAS
({91.220.109.0/24})

**Comment by kronby** [comment]
Thank you pulsar! This is workaround works for me.

**Comment by nickhilliard** [comment]
without realising, you stepped on a gigantic pile of dog poo which will never be cleaned up properly.  I've released 5.1.3 6b385e9, which hides the problem from public view.
