### ISSUE TITLE
peval don`t show any IPv4 address from ASN

### ISSUE THREAD

**Issue by takenek** [irrtoolset/irrtoolset#59]
This is a example:
peval AS136419
**NOT ANY**

But AS136419 got few IPv4 space:
103.87.236.0/23
103.87.236.0/24
103.87.237.0/24
103.87.238.0/24

Anyone know what is wrong?

**Comment by nickhilliard** [comment]
http://irrexplorer.nlnog.net/search/136419

```
103.87.236.0/24	136419	Prefix in DFZ, but no route-object with correct origin anywhere
103.87.237.0/24	136419	Prefix in DFZ, but no route-object with correct origin anywhere
103.87.238.0/24	136419	Prefix in DFZ, but no route-object with correct origin anywhere
```

The routes need to be registered at the APNIC IRR before peval will see them.

**Comment by takenek** [comment]
So what query i must give to see 103.87.236.0/24 ? other ASN ? i build firewall using peval and got abuse from this 103.87.236.0/24 and i want block everything from this same ASN. For now when i ask about 136419 don`t give me abuse IP address prefix...

**Comment by nickhilliard** [comment]
103.87.236.0/24 isn't registered in any LIR, so won't appear in any IRR query.  I'm not sure why you're building a firewall using peval - this is completely the wrong tool for the job.

**Comment by takenek** [comment]
And you are wrong i got many abuse from AS9009, when i block one ip address he use another from other country... and peval save my live :-)

**Comment by job** [comment]
@takenek maybe an easier to use tool is https://github.com/bgp/bgpq4 - this tool helps you query the IRR system and you can output the data in a custom format using FMT strings. It should be fairly trivial to build something to generate iptables rules from IRR to block certain ASNs.

**Comment by takenek** [comment]
Thanks :-) i take a look but this is not for Linux so i can use just:
bgpq4 -F"%n%1\n" AS136419
But this not resolve my main problem - how to find all prefix announce by AS136419.

**Comment by job** [comment]
You will not be able to use `peval` or `bgpq4` to output prefixes for which no IRR or RPKI registration exists anywhere. AS 136419 appears visible in the default-free zone, but they didnt register any of their routing intentions.

In cases like these you have to manually add their prefixes to your filters
