### ISSUE TITLE
Error: setting source to -* failed.

### ISSUE THREAD

**Issue by takenek** [irrtoolset/irrtoolset#65]
Hey guys,
In last few days i saw i get strange error:

root@zabbix:~# peval as12345
**Error: setting source to -* failed.

Error: current source setting is RADB,LACNIC,IDNIC,AFRINIC,RIPE,RIPE-NONAUTH,BELL,NTTCOM,ALTDB,PANIX,NESTEGG,LEVEL3,ARIN,JPIRR,BBOI,CANARIE,REACH,TC,APNIC.**

({212.47.32.0/19, 199.233.58.0/24, 199.233.59.0/24})

Best Regards
TaKeN

**Comment by SarkarKurdish** [comment]
We have the same issue it just appeared, did you fix it?

**Comment by nickhilliard** [comment]
Merit recently upgraded to IRRD v4. It looks like this whois daemon doesn't support the `!s-*` command:

v3: https://github.com/irrdnet/irrd-legacy/blob/main/src/programs/IRRd/commands.c#L1305
v4: https://github.com/irrdnet/irrd/blob/main/irrd/server/whois/query_parser.py#L362

You can ignore the warning.

Honestly, you'd be better off using bgpq4 for IRR queries. irrtoolset is bordering on being abandonware.
