### ISSUE TITLE
[macOS] Build failure: `rpsl.y: syntax error, unexpected string, expecting =`

### ISSUE THREAD

**Issue by barracuda156** [irrtoolset/irrtoolset#72]
Build fails on macOS 14 with clang:
```
  bison -y -d rpsl.y
  rpsl.y:93.14-19: syntax error, unexpected string, expecting =
  make[3]: *** [rpsl.y.cc] Error 1
  make[3]: *** Waiting for unfinished jobs....
  mv -f .deps/schema.Tpo .deps/schema.Plo
  mv -f .deps/rptype.Tpo .deps/rptype.Plo
  make[3]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_irrtoolset/irrtoolset/work/irrtoolset-5.1.3/src/rpsl'
  make[2]: *** [all-recursive] Error 1
```
Log: https://github.com/macports/macports-ports/actions/runs/11057228197/job/30720537640?pr=25945

**Comment by nickhilliard** [comment]
builds fine for me on sonoma / 14.6.1 (23G93).  Can you try building off the source and see if that works?

**Comment by barracuda156** [comment]
CI does build it from the source. Or do you mean something else?

P. S. The build worked fine for me locally, but on 10.6 with gcc.

**Comment by afpd** [comment]
Build will fail with bison 2.3 for example .
With bison  3.8.2, it will build. Install one from homebrew or other way.
Then run `confugure` as:
`YACC='/opt/homebrew/Cellar/bison/3.8.2/bin/bison -y' ./configure`
Surely with the correct path to a more recent bison.

**Comment by barracuda156** [comment]
Would be a bit surprising if the latest macOS have some archaic `bison`, but I will check that, thank you.

**Comment by afpd** [comment]
> Would be a bit surprising if the latest macOS have some archaic `bison`, but I will check that, thank you.

MacOS has absolutely archaic versions of everything GNU. Some other non-GNU opensource components are archaic too. Think like 10-16 years old archaic.

**Comment by nickhilliard** [comment]
```
% /usr/bin/bison --version | grep bison
bison (GNU Bison) 2.3
% /opt/local/bin/bison --version | grep bison
bison (GNU Bison) 3.8.2
```

You'll need to configure the port to have the macports version of bison as a build dependency in Portfile. Should build fine then.  There were some build instructions on irrtoolset.isc.org about this for various systems a couple of years ago, but ISC wiped the docs site (no major loss to humanity).

**Comment by barracuda156** [comment]
@nickhilliard Thank you, looks like it works now. Closing.
